### ISSUE TITLE
Brew install fails to download the latest release

### ISSUE THREAD

**Issue by amzaf** [tdjnodj/nekoray#37]
There seems to be a misconfiguration on the part of the brew installer as it fails to find and grab the latest release from the repository. Here is the error message

`am$ brew install nekoray --cask
Error: Download failed on Cask 'nekoray' with message: Failure while executing; `/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.18\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.7.6\)\ curl/7.87.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://github.com/tdjnodj/nekoray/releases/download/3.2/nekoray-3.2-2023.25-18-macos-amd64.dmg` exited with 22. Here's the output:
curl: (22) The requested URL returned error: 404`

**Comment by tdjnodj** [comment]
Try it now?
https://github.com/tdjnodj/homebrew-nekoray/commit/e562370999cf64c57922f11e27636b590f8dc670

**Comment by amzaf** [comment]
> Try it now? [tdjnodj/homebrew-nekoray@e562370](https://github.com/tdjnodj/homebrew-nekoray/commit/e562370999cf64c57922f11e27636b590f8dc670)

Now you have a new release 3.3, and a new error

`Error: Download failed on Cask 'nekoray' with message: Failure while executing; `/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.18\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.7.6\)\ curl/7.87.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://github.com/tdjnodj/nekoray/releases/download/3.3/nekoray-3.3-3.3-2023-05-18-macos-amd64.dmg` exited with 22. Here's the output:
curl: (22) The requested URL returned error: 404Error: Download failed on Cask 'nekoray' with message: Failure while executing; `/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.18\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.7.6\)\ curl/7.87.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://github.com/tdjnodj/nekoray/releases/download/3.3/nekoray-3.3-3.3-2023-05-18-macos-amd64.dmg` exited with 22. Here's the output:
curl: (22) The requested URL returned error: 404`

**Comment by tdjnodj** [comment]
https://github.com/tdjnodj/homebrew-nekoray/commit/5180804a889324c5d8f2908356f55dac3d041af7

**Comment by amzaf** [comment]
It's ok now. I hope this will not happen for the next release. Thank you.

**Comment by tdjnodj** [comment]
@amzaf I am sorry to waste your time(
